#!/usr/bin/env bash

# Nix
echo "Running Nix checks"

echo ""
echo "Running nix fmt..."
nixfmt \
  flake.nix \
  || exit 1

# Rust
echo "Running Rust checks"

echo ""
echo "Running Cargo.toml lint..."
cargo-toml-lint \
  Cargo.toml \
  || exit 1

echo ""
echo "Running cargo fmt..."
cargo fmt \
  || exit 1
