#!/usr/bin/env bash

# Rust
echo ""
echo "Running spellcheck..."
cargo spellcheck \
  || exit 1

echo ""
echo "Running check..."
cargo check \
  --release \
  --all-targets \
  --all-features \
  || exit 1

echo ""
echo "Running clippy..."
cargo clippy \
  --release \
  --all-targets \
  --all-features \
  --fix \
  --allow-dirty \
  || exit 1

echo ""
echo "Running tests..."
cargo test \
  --release \
  --bins \
  --examples \
  --tests \
  --all-features \
  || exit 1
