[package]
name = "search"
version = "0.1.0"
edition = "2024"
authors = [
		"Dietrich Daroch <Dietrich@Daroch.me>"
]
default-run = "main"
build = "build.rs"

[features]
# Allows inspecting data structure internals
inspect = []
verify = []

# Profiles
# --------
# https://doc.rust-lang.org/cargo/reference/profiles.html#default-profiles

# Dev
# https://doc.rust-lang.org/cargo/reference/profiles.html#profile-settings
[profile.dev]
debug-assertions = true
overflow-checks = true
panic = "unwind"
strip=false
split-debuginfo='packed'

# Release
# https://nnethercote.github.io/perf-book/build-configuration.html
[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
debug-assertions = false
overflow-checks = false
strip=true
panic = "abort"


[dependencies]
anstream = "0.6.18"
chrono = "0.4.41"
clap = { version = "4.5.37", features = ["derive", "env"] }
colorchoice-clap = "1.0.6"
derive_more = { version = "2.0.1", features = ["display"] }
image = "0.25.6"
indoc = "2.0.6"
nonmax = "0.5.5"
num-traits = "0.2.19"
owo-colors = "4.2.0"
rand = "0.9.1"
rand_chacha = "0.9.0"
rustc-hash = { version = "2.1.1", features = ["nightly"] }
shadow-rs = { version = "1.1.1", features = ["metadata"] }
smallvec = { version = "1.15.0", features = ["const_new"] }
thiserror = "2.0.12"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6", features = ["stats"] }

[build-dependencies]
shadow-rs = "1.1.1"


[[bin]]
name = "main"

[[bin]]
name = "report"
required-features = ["inspect"]
