# https://github.com/drahnr/cargo-spellcheck/blob/master/docs/configuration.md

dev_comments = true
skip_readme = false

[Spellbook]
lang = "en_GB"

[Hunspell]
lang = "en_GB"
skip_os_lookups = true
use_builtin = true

search_dirs = [".."]
extra_dictionaries = [
  ".spelling/dictionary.dic"  # ://.spelling/dictionary.dic
]
